//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festivals_Front_End.FestivalsBandsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FestivalsBandsServiceReference.IFestivalBandsService")]
    public interface IFestivalBandsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestivalBandsService/GenerateNewBandList", ReplyAction="http://tempuri.org/IFestivalBandsService/GenerateNewBandListResponse")]
        System.Collections.Generic.List<string> GenerateNewBandList(string Festival);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestivalBandsService/GenerateNewBandList", ReplyAction="http://tempuri.org/IFestivalBandsService/GenerateNewBandListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GenerateNewBandListAsync(string Festival);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFestivalBandsServiceChannel : Festivals_Front_End.FestivalsBandsServiceReference.IFestivalBandsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FestivalBandsServiceClient : System.ServiceModel.ClientBase<Festivals_Front_End.FestivalsBandsServiceReference.IFestivalBandsService>, Festivals_Front_End.FestivalsBandsServiceReference.IFestivalBandsService {
        
        public FestivalBandsServiceClient() {
        }
        
        public FestivalBandsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FestivalBandsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FestivalBandsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FestivalBandsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GenerateNewBandList(string Festival) {
            return base.Channel.GenerateNewBandList(Festival);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GenerateNewBandListAsync(string Festival) {
            return base.Channel.GenerateNewBandListAsync(Festival);
        }
    }
}
